"use client";

import { useEffect, useMemo, useState } from "react";
import { glossaryFor, PLAIN_TITLES } from "@/lib/beginner";
import type { TargetView } from "@/lib/db-types";
import { formatDate, gradeColor, scoreColor, SEV_COLOR, SEV_DOT, SEV_LABEL } from "@/lib/format";
import { CATEGORIES, SEVERITIES, type Finding, type Severity } from "@/lib/scanner/types";
import { CopyButton } from "./CopyButton";
import { RescanButton } from "./RescanButton";

export interface ReportData {
  url: string;
  host: string;
  scannedAt: string;
  score: number;
  grade: string;
  categoryScores: Record<string, number | null>;
  severityCounts: Record<Severity, number>;
  platforms: string[];
  requestCount?: number | null;
  findings: Finding[];
  targets?: TargetView[];
  comparison?: { previousScore: number; previousAt: string; scoreDelta: number; newFindings: Finding[]; resolvedFindings: Finding[]; unchanged: number } | null;
  /** Show the Re-scan buttons (owner view only). */
  canRescan?: boolean;
  /** "demo" shows a banner. */
  variant?: "owner" | "shared" | "demo";
  disclaimer: string;
}

type Mode = "beginner" | "technical";
type Filter = "issues" | "notes" | "passed";

export function Report({ data, actions }: { data: ReportData; actions?: React.ReactNode }) {
  const [mode, setMode] = useState<Mode>("beginner");
  const [filter, setFilter] = useState<Filter>("issues");

  useEffect(() => {
    try { const m = localStorage.getItem("vibesec-mode"); if (m === "technical" || m === "beginner") setMode(m); } catch { /* storage unavailable */ }
  }, []);
  const choose = (m: Mode) => { setMode(m); try { localStorage.setItem("vibesec-mode", m); } catch { /* ignore */ } };

  const issues = useMemo(() => data.findings.filter((f) => f.status === "fail" && f.severity !== "info"), [data.findings]);
  const notes = useMemo(() => data.findings.filter((f) => f.status === "info" || f.status === "unknown" || (f.status === "fail" && f.severity === "info")), [data.findings]);
  const passed = useMemo(() => data.findings.filter((f) => f.status === "pass"), [data.findings]);
  const list = filter === "issues" ? issues : filter === "notes" ? notes : passed;
  const topRisks = issues.slice(0, 3);
  const failCounts = SEVERITIES.filter((s) => s !== "info").map((s) => ({ s, n: data.severityCounts[s] ?? 0 }));

  return (
    <div className="mx-auto max-w-5xl px-5 py-10">
      {data.variant === "demo" && (
        <p className="mb-6 text-sm border-l-2 border-line-strong pl-3 text-muted">
          <strong className="text-fg font-medium">Demo report.</strong> Generated by running VibeSec&apos;s real rule engine on a sample site — no live website was scanned.
        </p>
      )}

      {/* ---- header */}
      <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
        <div className="min-w-0">
          <p className="text-sm text-muted">Security report</p>
          <h1 className="text-2xl sm:text-3xl font-semibold tracking-tight break-all">{data.host}</h1>
          <p className="text-sm text-muted mt-1 num">{formatDate(data.scannedAt)}{data.requestCount ? ` · ${data.requestCount} requests` : ""}</p>
        </div>
        <div className="flex flex-col gap-3 lg:items-end">
          <div role="group" aria-label="Report detail level" className="inline-flex rounded-md border border-line-strong p-0.5 text-sm self-start lg:self-auto">
            {(["beginner", "technical"] as const).map((m) => (
              <button key={m} onClick={() => choose(m)} aria-pressed={mode === m}
                className={`px-3 h-8 rounded capitalize ${mode === m ? "bg-raised text-fg" : "text-muted hover:text-fg"}`}>{m} mode</button>
            ))}
          </div>
          {actions}
        </div>
      </div>

      {/* ---- score */}
      <section className="mt-10 grid gap-10 lg:grid-cols-[auto_1fr] lg:gap-16 items-start" aria-label="Overall score">
        <div className="flex items-end gap-5">
          <div className={`num text-8xl font-semibold leading-none tracking-tighter ${scoreColor(data.score)}`}>{data.score}</div>
          <div className="pb-2">
            <div className={`text-5xl font-semibold leading-none ${gradeColor(data.grade)}`} aria-label={`Grade ${data.grade}`}>{data.grade}</div>
            <div className="text-xs text-muted mt-2 uppercase tracking-wider">out of 100</div>
          </div>
        </div>
        <div>
          <dl className="flex flex-wrap gap-x-8 gap-y-3">
            {failCounts.map(({ s, n }) => (
              <div key={s} className="flex items-baseline gap-2">
                <dt className="flex items-center gap-1.5 text-sm text-muted"><span className={`size-2 rounded-full ${n ? SEV_DOT[s] : "bg-line-strong"}`} />{SEV_LABEL[s]}</dt>
                <dd className={`num text-xl font-semibold ${n ? SEV_COLOR[s] : "text-faint"}`}>{n}</dd>
              </div>
            ))}
            <div className="flex items-baseline gap-2">
              <dt className="flex items-center gap-1.5 text-sm text-muted"><span className="size-2 rounded-full bg-ok" />Passed</dt>
              <dd className="num text-xl font-semibold text-ok">{passed.length}</dd>
            </div>
          </dl>
          <p className="mt-5 text-sm text-muted max-w-2xl">{data.disclaimer}</p>
        </div>
      </section>

      {/* ---- comparison */}
      {data.comparison && (
        <section className="mt-10 border-t border-line pt-6" aria-label="Comparison with previous scan">
          <h2 className="text-sm font-medium text-muted">Compared with previous scan <span className="num">({formatDate(data.comparison.previousAt)})</span></h2>
          <p className="mt-2 text-lg">
            <span className="num text-muted">{data.comparison.previousScore}</span> → <span className={`num font-semibold ${scoreColor(data.score)}`}>{data.score}</span>{" "}
            <span className={`num text-sm ${data.comparison.scoreDelta > 0 ? "text-ok" : data.comparison.scoreDelta < 0 ? "text-high" : "text-muted"}`}>
              ({data.comparison.scoreDelta > 0 ? "+" : ""}{data.comparison.scoreDelta})
            </span>
          </p>
          <div className="mt-4 grid sm:grid-cols-2 gap-6 text-sm">
            <DiffList title={`Resolved (${data.comparison.resolvedFindings.length})`} tone="ok" items={data.comparison.resolvedFindings} empty="Nothing resolved since last scan." />
            <DiffList title={`New (${data.comparison.newFindings.length})`} tone="risk" items={data.comparison.newFindings} empty="No new issues." />
          </div>
          <p className="mt-3 text-xs text-muted num">{data.comparison.unchanged} issue(s) unchanged.</p>
        </section>
      )}

      {/* ---- top risks */}
      {topRisks.length > 0 && (
        <section className="mt-10 border-t border-line pt-6" aria-label="Top risks">
          <h2 className="text-sm font-medium text-muted">Top risks — fix these first</h2>
          <ol className="mt-3 divide-y divide-line">
            {topRisks.map((f, i) => (
              <li key={f.fingerprint}>
                <a href={`#f-${slug(f.fingerprint)}`} onClick={() => setFilter("issues")} className="flex items-baseline gap-4 py-3 hover:bg-surface -mx-2 px-2 rounded">
                  <span className="num text-faint w-4">{i + 1}</span>
                  <span className={`text-xs font-medium w-16 shrink-0 ${SEV_COLOR[f.severity]}`}>{SEV_LABEL[f.severity]}</span>
                  <span className="flex-1">{displayTitle(f, mode)}</span>
                </a>
              </li>
            ))}
          </ol>
        </section>
      )}

      {/* ---- categories */}
      <section className="mt-10 border-t border-line pt-6" aria-label="Category scores">
        <h2 className="text-sm font-medium text-muted">Category scores</h2>
        <ul className="mt-4 grid gap-x-12 gap-y-4 sm:grid-cols-2">
          {CATEGORIES.map((c) => {
            const v = data.categoryScores[c];
            return (
              <li key={c}>
                <div className="flex justify-between text-sm mb-1.5">
                  <span>{c}</span>
                  <span className={`num ${v === null || v === undefined ? "text-faint" : scoreColor(v)}`}>{v ?? "n/a"}</span>
                </div>
                <div className="h-1 rounded bg-line" role="progressbar" aria-valuenow={v ?? 0} aria-valuemin={0} aria-valuemax={100} aria-label={`${c} score`}>
                  <div className={`h-1 rounded ${v === null || v === undefined ? "" : v >= 80 ? "bg-ok" : v >= 60 ? "bg-med" : "bg-crit"}`} style={{ width: `${v ?? 0}%` }} />
                </div>
              </li>
            );
          })}
        </ul>
      </section>

      {/* ---- findings */}
      <section className="mt-12 border-t border-line pt-6" aria-label="Findings">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <h2 className="text-lg font-semibold tracking-tight">Findings</h2>
          <div role="tablist" className="flex gap-1 text-sm">
            {([["issues", "Issues", issues.length], ["notes", "Notes", notes.length], ["passed", "Passed", passed.length]] as const).map(([k, label, n]) => (
              <button key={k} role="tab" aria-selected={filter === k} onClick={() => setFilter(k)}
                className={`px-3 h-8 rounded ${filter === k ? "bg-raised text-fg" : "text-muted hover:text-fg"}`}>{label} <span className="num text-faint">{n}</span></button>
            ))}
          </div>
        </div>
        {list.length === 0 ? (
          <p className="py-10 text-muted text-sm">{filter === "issues" ? "No issues found by these checks. That's good news — but remember this only covers what's visible from outside." : "Nothing here."}</p>
        ) : (
          <ul className="mt-4 divide-y divide-line border-y border-line">
            {list.map((f) => <FindingItem key={f.fingerprint} f={f} mode={mode} data={data} />)}
          </ul>
        )}
      </section>

      {/* ---- technical extras */}
      {mode === "technical" && (
        <section className="mt-12 border-t border-line pt-6" aria-label="Technical details">
          <h2 className="text-lg font-semibold tracking-tight">Technical details</h2>
          {data.platforms.length > 0 && <p className="mt-2 text-sm text-muted">Detected platforms (used to pick fix snippets): <span className="text-fg">{data.platforms.join(", ")}</span></p>}
          {data.platforms.length === 0 && <p className="mt-2 text-sm text-muted">No hosting platform could be identified reliably, so only generic header values are suggested.</p>}
          {(data.targets ?? []).length === 0 && data.variant === "shared" && <p className="mt-3 text-sm text-muted">Raw response headers are only available to the report owner.</p>}
          <div className="mt-4 space-y-3">
            {(data.targets ?? []).filter((t) => t.role !== "script").map((t, i) => (
              <details key={i} className="group border border-line rounded-md">
                <summary className="px-3 py-2.5 flex items-center gap-3 text-sm">
                  <span className="text-faint group-open:rotate-90 transition-transform">▸</span>
                  <span className="font-mono text-xs text-muted">{t.role}</span>
                  <span className="truncate flex-1">{t.final_url ?? t.url}</span>
                  <span className="num text-muted">{t.status_code ?? t.error_code ?? "—"}</span>
                </summary>
                <div className="px-3 pb-3 space-y-3">
                  {t.tls && <p className="text-xs text-muted font-mono">TLS: {t.tls.protocol} · {t.tls.cipher} · issuer: {t.tls.issuer ?? "?"} · valid until {t.tls.validTo ?? "?"}</p>}
                  <pre className="text-xs font-mono text-muted overflow-x-auto bg-surface rounded p-3 leading-relaxed">
                    {t.headers ? Object.entries(t.headers).flatMap(([k, v]) => (Array.isArray(v) ? v : [v]).map((x) => `${k}: ${x}`)).join("\n") : "(no headers recorded)"}
                  </pre>
                </div>
              </details>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}

function DiffList({ title, items, tone, empty }: { title: string; items: Finding[]; tone: "ok" | "risk"; empty: string }) {
  return (
    <div>
      <h3 className={`font-medium ${tone === "ok" ? "text-ok" : "text-high"}`}>{title}</h3>
      {items.length === 0 ? <p className="text-muted mt-1">{empty}</p> : (
        <ul className="mt-1 space-y-1">{items.slice(0, 8).map((f) => <li key={f.fingerprint} className="text-muted"><span className={SEV_COLOR[f.severity]}>{SEV_LABEL[f.severity]}</span> · {f.title}</li>)}</ul>
      )}
    </div>
  );
}

const slug = (s: string) => s.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
const displayTitle = (f: Finding, mode: Mode) => (mode === "beginner" ? PLAIN_TITLES[f.ruleId] ?? f.title : f.title);

function FindingItem({ f, mode, data }: { f: Finding; mode: Mode; data: ReportData }) {
  const isPass = f.status === "pass";
  const isFail = f.status === "fail";
  const glossary = mode === "beginner" ? glossaryFor(f.title, f.summary, f.remediation?.summary ?? "") : [];
  return (
    <li id={`f-${slug(f.fingerprint)}`} className="scroll-mt-20">
      <details className="group">
        <summary className="flex items-start gap-3 py-4 hover:bg-surface -mx-2 px-2 rounded">
          <span className="mt-2 shrink-0">
            {isPass ? <span className="block size-2 rounded-full bg-ok" aria-label="Passed" /> : <span className={`block size-2 rounded-full ${f.status === "unknown" ? "bg-line-strong" : SEV_DOT[f.severity]}`} aria-hidden />}
          </span>
          <span className="flex-1 min-w-0">
            <span className="flex flex-wrap items-baseline gap-x-3 gap-y-0.5">
              {isFail && <span className={`text-xs font-semibold uppercase tracking-wide ${SEV_COLOR[f.severity]}`}>{SEV_LABEL[f.severity]}</span>}
              {isPass && <span className="text-xs font-semibold uppercase tracking-wide text-ok">Passed</span>}
              {!isPass && !isFail && <span className="text-xs font-semibold uppercase tracking-wide text-info">{f.status === "unknown" ? "Not checked" : "Note"}</span>}
              <span className="font-medium">{displayTitle(f, mode)}</span>
            </span>
            <span className="block text-sm text-muted mt-0.5">{f.category}{mode === "technical" && <> · <span className="font-mono text-xs">{f.ruleId}</span> · confidence {f.confidence}</>}</span>
          </span>
          <span className="text-faint mt-1 group-open:rotate-90 transition-transform" aria-hidden>▸</span>
        </summary>

        <div className="pb-6 pl-5 sm:pl-6 space-y-5 text-[15px] leading-relaxed">
          <Section title="What we found"><p>{f.summary}</p></Section>
          <Section title="Why it matters"><p className="text-muted">{f.explanation}</p></Section>
          {glossary.length > 0 && (
            <div className="text-sm border-l-2 border-line-strong pl-3 space-y-1">
              {glossary.map((g) => <p key={g.term}><strong className="font-medium text-fg">{g.term}:</strong> <span className="text-muted">{g.meaning}</span></p>)}
            </div>
          )}
          {f.evidence.length > 0 && (
            <Section title="Evidence">
              <pre className="text-xs font-mono bg-surface rounded p-3 overflow-x-auto whitespace-pre-wrap break-all text-muted leading-relaxed">{f.evidence.join("\n")}</pre>
              {mode === "technical" && f.affectedUrl && <p className="mt-2 text-xs text-muted font-mono break-all">Affected URL: {f.affectedUrl}</p>}
            </Section>
          )}
          {mode === "technical" && f.technical && <Section title="Technical detail"><p className="text-sm text-muted font-mono whitespace-pre-wrap">{f.technical}</p></Section>}

          {f.remediation && !isPass && (
            <>
              <Section title="How to fix">
                <p>{f.remediation.summary}</p>
                {f.remediation.steps && <ul className="mt-2 list-disc pl-5 space-y-1 text-muted">{f.remediation.steps.map((s, i) => <li key={i}>{s}</li>)}</ul>}
              </Section>
              {f.remediation.snippets.length > 0 && (
                <Section title="Example fix">
                  <div className="space-y-3">
                    {f.remediation.snippets.map((s, i) => (
                      <div key={i}>
                        <div className="flex items-center justify-between gap-3 mb-1.5">
                          <span className="text-xs text-muted">{s.label}</span>
                          <CopyButton text={s.code} />
                        </div>
                        <pre className="text-xs font-mono bg-surface border border-line rounded p-3 overflow-x-auto leading-relaxed">{s.code}</pre>
                      </div>
                    ))}
                  </div>
                  {f.remediation.platformUnknown && <p className="mt-2 text-xs text-muted">We couldn&apos;t identify your hosting stack, so we only show the header itself — not a guessed config file.</p>}
                </Section>
              )}
              <Section title="Re-scan after fixing">
                <p className="text-sm text-muted mb-3">Deploy the change, wait a minute for caches to clear, then scan again to confirm this finding is resolved.</p>
                {data.canRescan ? <RescanButton url={data.url} variant="ghost" label="Re-scan this site" /> : <p className="text-xs text-faint">Sign in as the report owner to re-scan.</p>}
              </Section>
            </>
          )}
          {mode === "technical" && f.references.length > 0 && (
            <Section title="References">
              <ul className="space-y-1 text-sm">{f.references.map((r) => <li key={r.url}><a className="text-muted hover:text-fg underline underline-offset-2 break-all" href={r.url} target="_blank" rel="noopener noreferrer">{r.title}</a></li>)}</ul>
            </Section>
          )}
        </div>
      </details>
    </li>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="text-xs font-semibold uppercase tracking-wider text-faint mb-1.5">{title}</h3>
      {children}
    </div>
  );
}
