/**
 * Worker entrypoint. Wraps the OpenNext-built Next.js app and adds:
 *   - queue():     consumes scan jobs and drives the scanner Container
 *   - scheduled(): cron sweep (re-send lost jobs, fail hung ones) and retention purge
 *   - ScannerContainer: the Durable-Object-backed container class that runs container/server.ts
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`
import openNext from "../.open-next/worker.js";
import { Container, ContainerProxy, getRandom } from "@cloudflare/containers";
import * as repo from "../src/lib/db/repo";
import { processScanJob } from "../src/lib/jobs/run-scan-job";
import { createHybridScanner } from "../src/lib/jobs/hybrid-scanner";
import { createNdjsonScanner } from "../src/lib/jobs/scanner-client";
import { createDohResolver } from "../src/lib/ssrf/doh";
import { log } from "../src/lib/log";
import type { D1Like } from "../src/lib/db/d1";

export { ContainerProxy }; // required for the container's outbound policy (deniedHosts) to take effect

interface Env {
  DB: D1Like;
  SCAN_QUEUE: Queue<{ scanId: string }>;
  SCANNER: DurableObjectNamespace<ScannerContainer>;
  /** DEV ONLY (.dev.vars): send scans to a locally running `npm run scanner` instead of the Container. Never set in production. */
  LOCAL_SCANNER_URL?: string;
  NEXT_PUBLIC_SITE_URL?: string;
  /** "hybrid" (mặc định): Worker làm phần HTTP, container chỉ làm TLS. "container": quay về quét toàn bộ trong container (công tắc dự phòng). */
  SCAN_ENGINE?: string;
}

// 1 container xử lý song song 3 lượt (SCAN_CONCURRENCY): đánh thức nhiều container chỉ làm tăng chi phí RAM.
const SCANNER_POOL_SIZE = 1;

/** Private/loopback/metadata ranges the scanner must never reach. Second line of defence behind the in-code SSRF checks. */
const DENIED = [
  "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "127.0.0.0/8", "169.254.0.0/16", "100.64.0.0/10", "0.0.0.0/8",
  "metadata.google.internal", "metadata", "*.internal", "*.local", "*.localhost",
];

export class ScannerContainer extends Container {
  defaultPort = 8080;
  sleepAfter = "10s"; // RAM tính tiền cả lúc chờ: ngủ sớm để tiết kiệm (quét lai chỉ cần vài giây)
  pingEndpoint = "localhost/ready";
  envVars = { NODE_ENV: "production", SCAN_CONCURRENCY: "3" };
  // Internet is required to scan public sites. deniedHosts is enforced for HTTP:80 (and for 443 only with
  // interceptHttps, which we deliberately leave OFF so TLS certificate/version inspection sees the real handshake).
  enableInternet = true;
  deniedHosts = DENIED;
}

export default {
  fetch: openNext.fetch,

  async queue(batch, env): Promise<void> {
    for (const msg of batch.messages) {
      try {
        // Container chỉ được đánh thức khi thật sự gọi `send` (lười): quét lai thường chỉ cần /tls, và thường còn trúng đệm.
        const send = env.LOCAL_SCANNER_URL
          ? (req: Request) => fetch(new URL(new URL(req.url).pathname, env.LOCAL_SCANNER_URL), { method: req.method, headers: req.headers, body: req.body })
          : async (req: Request) => (await getRandom(env.SCANNER, SCANNER_POOL_SIZE)).fetch(req);
        const selfHost = env.NEXT_PUBLIC_SITE_URL ? new URL(env.NEXT_PUBLIC_SITE_URL).hostname : null;
        const scanner = env.SCAN_ENGINE === "container"
          ? createNdjsonScanner(send)
          : createHybridScanner({ db: env.DB, resolver: createDohResolver(), container: send, denyHosts: selfHost ? [selfHost] : [] });
        const outcome = await processScanJob(env.DB, msg.body.scanId, scanner);
        if (outcome === "retry") msg.retry({ delaySeconds: 15 * msg.attempts });
        else msg.ack();
      } catch (e) {
        // Unexpected (e.g. D1 hiccup). Let Queues redeliver; after max_retries it lands in the dead-letter queue.
        log("error", "queue_handler_error", { scan: msg.body.scanId, name: (e as Error).name, attempt: msg.attempts });
        msg.retry({ delaySeconds: 30 });
      }
    }
  },

  async scheduled(event, env, ctx): Promise<void> {
    ctx.waitUntil(
      (async () => {
        if (event.cron === "17 * * * *") {
          const purged = await repo.purgeExpired(env.DB);
          log("info", "retention_purge", purged);
          return;
        }
        const hung = await repo.reapHung(env.DB, 10 * 60_000);
        const lost = await repo.staleQueued(env.DB, 2 * 60_000);
        for (const scanId of lost) await env.SCAN_QUEUE.send({ scanId }); // claim is idempotent, so a duplicate is harmless
        if (hung || lost.length) log("warn", "queue_sweep", { hung, resent: lost.length });
      })(),
    );
  },
} satisfies ExportedHandler<Env, { scanId: string }>;
